version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    restart: always

  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    restart: always

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/higor1234
    restart: always